server_ip = "127.0.0.1"
server_port = "8000"
cache_valid_period_sec = 10

servers = [
    # $IP$ - placeholder for IP address
    "http://ip-api.com/json/$IP$",
    "http://ipapi.co/$IP$/json/",
    "http://ipfind.co/?ip=$IP$"
]